### ISSUE TITLE
CBB?

### ISSUE THREAD

**Issue by str** [konradbaron/php-fantasydata#1]
Could this work for CBB?

**Comment by konradbaron** [comment]
Hi, I'm not sure what CBB is. But the data is coming from
https://fantasydata.com/ and I don't see "CBB" listed there, so it probably
wouldn't work.

**Comment by str** [comment]
Sorry, I meant NCAA. It is listed as "NCAA Basketball" at https://developer.fantasydata.com/documentation, but once I click the documentation link it's shown as CBB (college basketball) https://developer.fantasydata.com/docs/services/594406ffc5ea71b9ec624405/operations/5944071635491a0cc050ffcc

**Comment by konradbaron** [comment]
No, NCAA Basketball isn't in there yet but it supports NBA. If you wanted you could probably use the NBA as a template for building NCAA Basketball
